default_language_version:
  python: python3
repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: ingestion/src/metadata/generated
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        exclude: ingestion/src/metadata/generated
  - repo: https://github.com/hadialqattan/pycln
    rev: v1.2.4
    hooks:
      - id: pycln
        exclude: ingestion/src/metadata/generated
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        files: ^openmetadata-service/src/main/resources/json/schema/
  - repo: local
    hooks:
      - id: google-style-java
        name: Google Java Code Style for Java
        description: Formats code in Google's Java codestyle with 100 line length.
        entry: scripts/format-code.sh
        language: script
        files: \.java$
        require_serial: true
  - repo: local
    hooks:
      - id: lint-staged
        name: lint-staged
        description: Formats TS and JS code.
        entry: scripts/lint-staged.sh
        language: script
        files: \.(js|jsx|ts|tsx)$
        require_serial: true
