#  Copyright 2021 Collate
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

name: docker-openmetadata-postgres-db docker
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Input tag"
        required: true
      push_latest_tag_to_release:
        description: "Do you want to update docker image latest tag as well ?"
        type: boolean
  release:
    types: [published]

jobs:
  push_to_docker_hub:
    runs-on: ubuntu-latest
    env:
      input: ${{ github.event.inputs.tag }}
    
    steps:
      - name: Check trigger type
        if: ${{ env.input == '' }}
        run: echo "input=0.13.3" >> $GITHUB_ENV
        
      - name: Check out the Repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_OPENMETADATA_USERNAME }}
          password: ${{ secrets.DOCKERHUB_OPENMETADATA_TOKEN }}
      
      - name: Process Docker Tags
        id:  input_check
        run: |
            if ${{ github.event_name == 'release' }}; then
                echo "tags=openmetadata/postgresql:${{ env.input }},openmetadata/postgresql:latest" >> $GITHUB_OUTPUT
            elif ${{ github.event_name == 'workflow_dispatch' && inputs.push_latest_tag_to_release }}; then
                echo "tags=openmetadata/postgresql:${{inputs.tag}},openmetadata/postgresql:latest" >> $GITHUB_OUTPUT
            else
                echo "tags=openmetadata/postgresql:${{ inputs.tag }}" >> $GITHUB_OUTPUT
            fi

      - name: Build and push if event is workflow_dispatch and input is checked
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'release' || github.event_name == 'workflow_dispatch' }}
          tags: ${{ steps.input_check.outputs.tags }}
          file: ./docker/local-metadata/Dockerfile_postgres