#  Copyright 2021 Collate
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

name: ESLint and Prettier

on:
  # Trigger analysis when creating or updating a pull request.
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'openmetadata-ui/src/main/resources/ui/**'

permissions:
  contents: read

concurrency: 
  group: eslint-prettier-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  eslint-prettier:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

      steps:
        - name: Free Disk Space (Ubuntu)
          uses: jlumbroso/free-disk-space@main
          with:
              tool-cache: false
              android: true
              dotnet: true
              haskell: true
              large-packages: false
              swap-storage: true
              docker-images: false

        - name: Checkout
          uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'openmetadata-ui/src/main/resources/ui/.nvmrc'
          cache: 'yarn'
          cache-dependency-path: 'openmetadata-ui/src/main/resources/ui/yarn.lock'

      - name: Install dependencies
        working-directory: openmetadata-ui/src/main/resources/ui
        run: yarn install --frozen-lockfile

      - name: Run ESLint
        id: eslint
        continue-on-error: true
        working-directory: openmetadata-ui/src/main/resources/ui
        run: yarn run lint

      - name: Run Prettier check
        id: prettier
        continue-on-error: true
        working-directory: openmetadata-ui/src/main/resources/ui
        run: npx prettier . --config './.prettierrc.yaml' --ignore-path './.prettierignore' --check

      - name: Run License Header check
        id: license
        continue-on-error: true
        working-directory: openmetadata-ui/src/main/resources/ui
        run: yarn run license-header-check

      - name: Check import organization
        id: imports
        continue-on-error: true
        working-directory: openmetadata-ui/src/main/resources/ui
        run: npx organize-imports-cli --check 'src/**/*.{ts,tsx,js,jsx}'

      - name: Save check outcome
        id: git
        continue-on-error: true
        run: |
          git diff-files --quiet

      - name: Create a comment in the PR with the instructions
        if: steps.eslint.outcome != 'success' || steps.prettier.outcome != 'success' || steps.license.outcome != 'success' || steps.imports.outcome != 'success' || steps.git.outcome != 'success'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **The ESLint/Prettier checks failed.**

            Please run `make lint-fix` in the root of your repository to automatically fix linting issues, or run the following commands manually:
            ```bash
            cd openmetadata-ui/src/main/resources/ui
            yarn run lint:fix
            yarn run pretty
            yarn run license-header-fix
            npx organize-imports-cli 'src/**/*.{ts,tsx,js,jsx}'
            ```

            Then commit the changes to this PR.

            You can also use [pre-commit](https://pre-commit.com/) to automate the code formatting.
            You can install the pre-commit hooks with `make install_test precommit_install`.

      - name: ESLint/Prettier checks failed, check the comment in the PR
        if: steps.eslint.outcome != 'success' || steps.prettier.outcome != 'success' || steps.license.outcome != 'success' || steps.imports.outcome != 'success' || steps.git.outcome != 'success'
        run: |
          exit 1
