# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Selenium Java CI

on:
  push:
    branches: [main]
    paths:
      - 'catalog-rest-service/src/main/resource/ui/**'
      - 'catalog-rest-service/src/test/java/org/openmetadata/catalog/selenium/pages/**'
      - 'docker/**'
  pull_request:
    branches: [main]
    paths:
      - 'catalog-rest-service/src/main/resource/ui/**'
      - 'catalog-rest-service/src/test/java/org/openmetadata/catalog/selenium/pages/**'
      - 'docker/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Generating Data Models
      run: make install_dev generate

    - name: Start Server and Ingest Sample Data
      run: ./docker/run_local_docker.sh

    - name: Run Page Tests
      run: mvn clean test -Dtest="org.openmetadata.catalog.selenium.pages.**.*.java" -DfailIfNoTests=false

